services:
  - type: web
    name: economia-energy
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./db/custom.db
      - key: HUBPAGUE_TOKEN
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: PORT
        value: 10000
